server:
    port: 5600
    context-path: eurekaserver
    # ???? 8761
spring:
    application:
        name: eurekaserver # ???????Eureka??????id???serviceId?
eureka:
    client:
        service-url: # EurekaServer????????????????????????Server????
            defaultZone: http://127.0.0.1:5600/eurekaserver/eureka/
        register-with-eureka: false # ?????  ???? true
        fetch-registry: false #?????  ???? true

